# Generated by Django 3.1 on 2020-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created date')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified date')),
                ('start_date', models.DateField(blank=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, verbose_name='end date')),
                ('disc_percent', models.FloatField(blank=True)),
                ('disc_min_order_amount', models.IntegerField(blank=True)),
                ('disc_max_limit', models.IntegerField(blank=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CouponInfo',
            },
        ),
    ]
