# Generated by Django 3.1 on 2020-09-29 20:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0003_couponinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created date')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified date')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapiservice.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapiservice.orderinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CustomerRating',
            },
        ),
    ]
