# Generated by Django 3.1 on 2020-10-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0004_customerrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SpecificationCategory',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('detail', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created date')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified date')),
                ('isActive', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapiservice.specificationcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapiservice.product')),
            ],
            options={
                'db_table': 'ProductSpecification',
            },
        ),
    ]
