# Generated by Django 3.1 on 2020-10-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0005_productspecification_specificationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponinfo',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='averageRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
