# Generated by Django 3.1 on 2020-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0007_orderinfo_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified date')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CustomerSubscribe',
            },
        ),
    ]
