# Generated by Django 3.1 on 2020-10-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0008_customersubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gstPercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
