# Generated by Django 3.1 on 2020-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0009_product_gstpercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
