# Generated by Django 3.1.2 on 2021-03-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0010_userinfo_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='shipping_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
