# Generated by Django 3.1.2 on 2021-09-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0011_orderinfo_shipping_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancellationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created date')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified date')),
                ('refund_id', models.TextField(blank=True, null=True)),
                ('refund_status', models.TextField(blank=True, null=True)),
                ('comment', models.CharField(max_length=255)),
                ('request_status', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapiservice.orderinfo')),
            ],
            options={
                'db_table': 'OrderCancellationRequest',
            },
        ),
    ]
