# Generated by Django 3.1.2 on 2021-09-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiservice', '0012_ordercancellationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercancellationrequest',
            name='request_time_track_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
